from __future__ import annotations

import argparse
import math
import sqlite3
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt


@dataclass(frozen=True)
class PolicySpec:
    policy_dir: str
    pretty: str


POLICIES_ONLY_WORKERS: list[PolicySpec] = [
    PolicySpec("LEAST_LOADED_NOT_AWARE", "LL"),
    PolicySpec("MAXIMUM_LIFESPANE", "ML"),
    PolicySpec("RANDOM", "RAND"),
    PolicySpec("SCORE_SIMPLE", "LBF"),
]

POLICIES_WORKERS_OR_CLOUD: list[PolicySpec] = [
    PolicySpec("LEAST_LOADED_AWARE_CLOUD", "LLAC"),
    PolicySpec("MAXIMUM_LIFESPANE", "ML"),
    PolicySpec("RANDOM", "RAND"),
    PolicySpec("LBFC", "LBFC"),
]


def _latest_db_for(
    no_learning_root: Path,
    policy_dir: str,
    scenario_suffix: str,
    name_contains: str | None,
    run_name_contains: str | None,
    failure_mode: str,
) -> Path:
    """
    Discover the latest run directory under:
      <no_learning_root>/<policy_dir>/
    matching:
      - endswith(scenario_suffix)
      - and optionally containing `name_contains`
    """
    policy_root = no_learning_root / policy_dir
    if not policy_root.exists():
        raise FileNotFoundError(f"Policy directory not found: {policy_root}")

    runs = []
    for p in policy_root.iterdir():
        if not p.is_dir():
            continue
        # Runs may include extra tags after the scenario suffix (e.g. "..._FAILURE_110_100_070").
        # So we match by containment instead of strict suffix.
        has_scenario = scenario_suffix in p.name
        has_failure = "_FAILURE" in p.name
        is_failure = has_scenario and has_failure
        is_non_failure = has_scenario and not has_failure

        if failure_mode == "only":
            if not is_failure:
                continue
        elif failure_mode == "non":
            if not is_non_failure:
                continue
        elif failure_mode == "any":
            if not (is_non_failure or is_failure):
                continue
        else:
            raise RuntimeError(f"Invalid failure_mode='{failure_mode}', expected: any|only|non")

        if name_contains and name_contains not in p.name:
            continue
        if run_name_contains and run_name_contains not in p.name:
            continue
        runs.append(p)

    runs = sorted(runs)
    if not runs:
        extra = f" containing '{name_contains}'" if name_contains else ""
        raise FileNotFoundError(f"No run found under {policy_root} ending with '{scenario_suffix}'{extra}")

    db_path = runs[-1] / "log.db"
    if not db_path.exists():
        raise FileNotFoundError(f"Missing log.db: {db_path}")
    return db_path


def _simulation_time_s(db_path: Path, scheduler_uid: int) -> int:
    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()
        cur.execute("SELECT MAX(generated_at) FROM jobs WHERE node_uid = ?", (scheduler_uid,))
        row = cur.fetchone()
        tmax = float(row[0] or 0.0)
    finally:
        con.close()
    return int(math.ceil(tmax))


def _counts_per_second_gamma_eff(
    db_path: Path,
    scheduler_uid: int,
    warmup_time_s: float,
) -> tuple[dict[int, int], dict[int, int]]:
    """
    Return per-second counts for effective QoS:
      - total_jobs[t] = #jobs generated by the scheduler
      - ontime[t] = #jobs completed on time (rejected=0, done=1, over_deadline=0)

    gamma_eff(t) is computed as ontime / total_jobs.
    """
    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()

        total_jobs: dict[int, int] = {}
        ontime: dict[int, int] = {}

        cur.execute(
            """
            SELECT CAST(generated_at AS INTEGER) AS t, COUNT(*)
            FROM jobs
            WHERE node_uid = ? AND generated_at > ?
            GROUP BY CAST(generated_at AS INTEGER)
            """,
            (scheduler_uid, warmup_time_s),
        )
        for t, c in cur.fetchall():
            total_jobs[int(t)] = int(c)

        cur.execute(
            """
            SELECT CAST(generated_at AS INTEGER) AS t, COUNT(*)
            FROM jobs
            WHERE node_uid = ? AND generated_at > ?
              AND rejected = 0 AND done = 1 AND over_deadline = 0
            GROUP BY CAST(generated_at AS INTEGER)
            """,
            (scheduler_uid, warmup_time_s),
        )
        for t, c in cur.fetchall():
            ontime[int(t)] = int(c)
    finally:
        con.close()

    return total_jobs, ontime


def _windowed_ratio(
    denom_per_s: dict[int, int],
    numer_per_s: dict[int, int],
    simulation_time_s: int,
    window_s: int,
) -> tuple[list[int], list[float]]:
    x: list[int] = []
    y: list[float] = []

    if window_s <= 0:
        window_s = 1

    sum_d = 0
    sum_n = 0
    for t in range(simulation_time_s + 1):
        sum_d += denom_per_s.get(t, 0)
        sum_n += numer_per_s.get(t, 0)

        if t > 0 and (t % window_s == 0):
            if sum_d <= 0:
                val = float("nan")
            else:
                val = float(sum_n) / float(sum_d)
            x.append(t)
            y.append(val)
            sum_d = 0
            sum_n = 0

    return x, y


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Plot no-learning gamma(t) over time as 4 subplots (one per policy). "
            "Works for ONLY_WORKERS and WORKERS_OR_CLOUD. Optionally filter runs by a tag (e.g. FAILURE)."
        )
    )
    parser.add_argument(
        "--no-learning-root",
        type=Path,
        default=Path("results/data/_log/no-learning"),
        help="Root directory containing no-learning logs.",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        choices=["ONLY_WORKERS", "WORKERS_OR_CLOUD"],
        default="WORKERS_OR_CLOUD",
        help="Scenario suffix to pick the right run directories.",
    )
    parser.add_argument(
        "--name-contains",
        type=str,
        default="FAILURE",
        help=(
            "Optional substring that must appear in the run directory name. "
            "Use 'FAILURE' for failure runs; pass '' to disable filtering."
        ),
    )
    parser.add_argument(
        "--failure-mode",
        type=str,
        choices=["any", "only", "non"],
        default="any",
        help=(
            "Choose which run type to pick when both are present: "
            "'non' for *_<SCENARIO>, 'only' for *_<SCENARIO>_FAILURE, 'any' for either."
        ),
    )
    parser.add_argument(
        "--run-name-contains",
        type=str,
        default="",
        help=(
            "Extra substring to select a specific run among multiple dates/tags. "
            "Example: '--run-name-contains 20260429' or '--run-name-contains PAIR_'. "
            "Empty string disables this filter."
        ),
    )
    parser.add_argument(
        "--window-s",
        type=int,
        default=300,
        help="Window size in seconds for averaging gamma(t).",
    )
    parser.add_argument(
        "--warmup-time-s",
        type=float,
        default=0.0,
        help="Ignore initial transient by filtering generated_at > warmup_time_s.",
    )
    parser.add_argument(
        "--scheduler-uid",
        type=int,
        default=0,
        help="Scheduler node UID in the jobs table.",
    )
    parser.add_argument(
        "--t-fail",
        type=float,
        default=None,
        help="Optional failure time (s) to draw a vertical marker.",
    )
    parser.add_argument(
        "--t-recover",
        type=float,
        default=None,
        help="Optional recovery time (s) to draw a vertical marker.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results/plot"),
        help="Output directory for thesis plots.",
    )
    parser.add_argument(
        "--out-stem",
        type=str,
        default="gamma_over_time_4subplots",
        help="Output filename stem (without extension).",
    )
    parser.add_argument(
        "--figsize",
        type=str,
        default="10,6.5",
        help="Figure size in inches as 'W,H' (e.g. '10,6.5').",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=200,
        help="DPI for PNG output.",
    )
    args = parser.parse_args()

    scenario_suffix = f"_{args.scenario}"
    name_contains = args.name_contains if args.name_contains.strip() else None
    run_name_contains = args.run_name_contains if args.run_name_contains.strip() else None

    policies = POLICIES_ONLY_WORKERS if args.scenario == "ONLY_WORKERS" else POLICIES_WORKERS_OR_CLOUD

    policy_to_db: list[tuple[PolicySpec, Path]] = []
    for spec in policies:
        policy_to_db.append(
            (
                spec,
                _latest_db_for(
                    no_learning_root=args.no_learning_root,
                    policy_dir=spec.policy_dir,
                    scenario_suffix=scenario_suffix,
                    name_contains=name_contains,
                    run_name_contains=run_name_contains,
                    failure_mode=args.failure_mode,
                ),
            )
        )

    series_by_policy: list[tuple[PolicySpec, list[int], list[float]]] = []
    global_t_max = 0
    for spec, db_path in policy_to_db:
        sim_t = _simulation_time_s(db_path, scheduler_uid=args.scheduler_uid)
        denom_s, numer_s = _counts_per_second_gamma_eff(
            db_path=db_path,
            scheduler_uid=args.scheduler_uid,
            warmup_time_s=args.warmup_time_s,
        )
        x, y = _windowed_ratio(
            denom_per_s=denom_s,
            numer_per_s=numer_s,
            simulation_time_s=sim_t,
            window_s=args.window_s,
        )
        series_by_policy.append((spec, x, y))
        if x:
            global_t_max = max(global_t_max, max(x))

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out_pdf = args.out_dir / f"{args.out_stem}.pdf"
    out_png = args.out_dir / f"{args.out_stem}.png"

    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": 14,
            "axes.labelsize": 12,
            "legend.fontsize": 11,
            "xtick.labelsize": 11,
            "ytick.labelsize": 11,
            "lines.linewidth": 1.6,
        }
    )

    try:
        fig_w_s, fig_h_s = args.figsize.split(",", 1)
        fig_w = float(fig_w_s.strip())
        fig_h = float(fig_h_s.strip())
    except Exception as e:
        raise SystemExit(f"Invalid --figsize '{args.figsize}', expected 'W,H'") from e

    fig, axes = plt.subplots(nrows=2, ncols=2, sharex=True, sharey=True, figsize=(fig_w, fig_h))
    axes_list = [axes[0][0], axes[0][1], axes[1][0], axes[1][1]]

    gamma_color = "#1f77b4"
    fail_color = "#d62728"
    rec_color = "#2ca02c"

    for ax, (spec, x, y) in zip(axes_list, series_by_policy):
        ax.plot(x, y, color=gamma_color, marker="o", markersize=3.0)
        ax.set_title(spec.pretty, fontweight="semibold")
        ax.grid(color="#cacaca", linestyle="--", linewidth=0.6, alpha=0.8)
        ax.set_ylim(0.0, 1.0)

        if args.t_fail is not None:
            ax.axvline(float(args.t_fail), color=fail_color, linestyle="--", linewidth=1.2)
        if args.t_recover is not None:
            ax.axvline(float(args.t_recover), color=rec_color, linestyle="--", linewidth=1.2)

    fig.supxlabel("Time (s)", y=0.08)
    fig.supylabel(r"$\gamma_{\mathrm{eff}}(t)$")

    # Shared x-limits for fair comparison.
    if global_t_max > 0:
        for ax in axes_list:
            ax.set_xlim(0.0, float(global_t_max))

    # Figure-level legend (optional markers).
    handles = [
        plt.Line2D([0], [0], color=gamma_color, linewidth=2.0, label=r"$\gamma_{\mathrm{eff}}(t)$")
    ]
    labels = [r"$\gamma_{\mathrm{eff}}(t)$"]
    if args.t_fail is not None:
        handles.append(
            plt.Line2D([0], [0], color=fail_color, linestyle="--", linewidth=1.8, label="Failure")
        )
        labels.append("Failure")
    if args.t_recover is not None:
        handles.append(
            plt.Line2D([0], [0], color=rec_color, linestyle="--", linewidth=1.8, label="Recovery")
        )
        labels.append("Recovery")
    fig.legend(
        handles=handles,
        labels=labels,
        loc="lower center",
        ncol=len(handles),
        frameon=False,
        bbox_to_anchor=(0.5, 0.02),
    )

    fig.tight_layout(rect=(0.0, 0.14, 1.0, 1.0))
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_png, dpi=args.dpi, bbox_inches="tight")
    plt.close(fig)

    print(f"[OK] Wrote {out_pdf}")
    print(f"[OK] Wrote {out_png}")
    for spec, db_path in policy_to_db:
        print(f"[DB] {spec.pretty}: {db_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

