from __future__ import annotations

import argparse
import math
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt


def _simulation_time_s(db_path: Path, scheduler_uid: int) -> int:
    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()
        cur.execute("SELECT MAX(generated_at) FROM jobs WHERE node_uid = ?", (scheduler_uid,))
        row = cur.fetchone()
        tmax = float(row[0] or 0.0)
    finally:
        con.close()
    return int(math.ceil(tmax))


def _counts_per_second_gamma_eff(
    db_path: Path, scheduler_uid: int, warmup_time_s: float
) -> tuple[dict[int, int], dict[int, int]]:
    """
    gamma_eff(t) = ontime / total_jobs, computed per window.

    - total_jobs: all jobs generated by scheduler (node_uid)
    - ontime: rejected=0 AND done=1 AND over_deadline=0
    """
    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()
        total: dict[int, int] = {}
        ontime: dict[int, int] = {}

        cur.execute(
            """
            SELECT CAST(generated_at AS INTEGER) AS t, COUNT(*)
            FROM jobs
            WHERE node_uid = ? AND generated_at > ?
            GROUP BY CAST(generated_at AS INTEGER)
            """,
            (scheduler_uid, warmup_time_s),
        )
        for t, c in cur.fetchall():
            total[int(t)] = int(c)

        cur.execute(
            """
            SELECT CAST(generated_at AS INTEGER) AS t, COUNT(*)
            FROM jobs
            WHERE node_uid = ? AND generated_at > ?
              AND rejected = 0 AND done = 1 AND over_deadline = 0
            GROUP BY CAST(generated_at AS INTEGER)
            """,
            (scheduler_uid, warmup_time_s),
        )
        for t, c in cur.fetchall():
            ontime[int(t)] = int(c)
    finally:
        con.close()

    return total, ontime


def _windowed_ratio(
    denom_per_s: dict[int, int],
    numer_per_s: dict[int, int],
    simulation_time_s: int,
    window_s: int,
) -> tuple[list[int], list[float]]:
    x: list[int] = []
    y: list[float] = []

    if window_s <= 0:
        window_s = 1

    sum_d = 0
    sum_n = 0
    for t in range(simulation_time_s + 1):
        sum_d += denom_per_s.get(t, 0)
        sum_n += numer_per_s.get(t, 0)

        if t > 0 and (t % window_s == 0):
            val = float("nan") if sum_d <= 0 else float(sum_n) / float(sum_d)
            x.append(t)
            y.append(val)
            sum_d = 0
            sum_n = 0
    return x, y


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot gamma_eff(t) for a single log.db.")
    parser.add_argument("--db-path", type=Path, required=True, help="Path to log.db")
    parser.add_argument("--window-s", type=int, default=120, help="Window size in seconds")
    parser.add_argument("--warmup-time-s", type=float, default=0.0, help="Ignore generated_at <= warmup_time_s")
    parser.add_argument("--scheduler-uid", type=int, default=0, help="Scheduler node UID in jobs table")
    parser.add_argument("--t-fail", type=float, default=None, help="Failure time marker (s)")
    parser.add_argument("--t-recover", type=float, default=None, help="Recovery time marker (s)")
    parser.add_argument("--out", type=Path, default=Path("results/plot/gamma_eff_over_time_single.pdf"))
    parser.add_argument("--dpi", type=int, default=200, help="DPI for PNG output (if --out endswith .png)")
    args = parser.parse_args()

    sim_t = _simulation_time_s(args.db_path, scheduler_uid=args.scheduler_uid)
    total_s, ontime_s = _counts_per_second_gamma_eff(
        args.db_path, scheduler_uid=args.scheduler_uid, warmup_time_s=args.warmup_time_s
    )
    x, y = _windowed_ratio(total_s, ontime_s, simulation_time_s=sim_t, window_s=args.window_s)

    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": 14,
            "axes.labelsize": 12,
            "xtick.labelsize": 11,
            "ytick.labelsize": 11,
            "lines.linewidth": 1.6,
        }
    )
    # Slightly taller canvas so x-label + legend don't collide when markers are enabled.
    fig, ax = plt.subplots(figsize=(9.0, 3.6))
    ax.plot(x, y, color="#1f77b4", marker="o", markersize=3.0)
    ax.grid(color="#cacaca", linestyle="--", linewidth=0.6, alpha=0.8)
    ax.set_ylabel(r"$\gamma_{\mathrm{eff}}(t)$")
    ax.set_ylim(0.0, 1.0)
    if args.t_fail is not None:
        ax.axvline(float(args.t_fail), color="#d62728", linestyle="--", linewidth=1.2, label="Failure")
    if args.t_recover is not None:
        ax.axvline(float(args.t_recover), color="#2ca02c", linestyle="--", linewidth=1.2, label="Recovery")
    if args.t_fail is not None or args.t_recover is not None:
        # Keep legend inside the axes to avoid overlapping the x-axis label.
        ax.legend(frameon=False, loc="upper right", fontsize="small")
        fig.supxlabel("Time (s)", y=0.02)
        fig.tight_layout(rect=(0.0, 0.06, 1.0, 1.0))
    else:
        ax.set_xlabel("Time (s)")
        fig.tight_layout()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    if args.out.suffix.lower() == ".png":
        fig.savefig(args.out, dpi=args.dpi, bbox_inches="tight")
    else:
        fig.savefig(args.out, bbox_inches="tight")
    plt.close(fig)

    print(f"[OK] Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

